[2024-12-31T09:15:47.682+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-31T09:15:47.688+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.run_pyspark_etl manual__2024-12-31T08:06:36.183790+00:00 [queued]>
[2024-12-31T09:15:47.691+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.run_pyspark_etl manual__2024-12-31T08:06:36.183790+00:00 [queued]>
[2024-12-31T09:15:47.691+0100] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2024-12-31T09:15:47.701+0100] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): run_pyspark_etl> on 2024-12-31 08:06:36.183790+00:00
[2024-12-31T09:15:47.704+0100] {standard_task_runner.py:72} INFO - Started process 14653 to run task
[2024-12-31T09:15:47.706+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'pyspark_etl_pipeline', 'run_pyspark_etl', 'manual__2024-12-31T08:06:36.183790+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmp3pioekhf']
[2024-12-31T09:15:47.707+0100] {standard_task_runner.py:105} INFO - Job 58: Subtask run_pyspark_etl
[2024-12-31T09:15:47.748+0100] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.run_pyspark_etl manual__2024-12-31T08:06:36.183790+00:00 [running]> on host NB04
[2024-12-31T09:15:47.784+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_pyspark_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T08:06:36.183790+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-31T08:06:36.183790+00:00'
[2024-12-31T09:15:47.785+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-31T09:15:47.794+0100] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-12-31T09:15:47.795+0100] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /home/maxpower/airflow/dags/amazon_v2_cleanup.py
[2024-12-31T09:15:48.512+0100] {spark_submit.py:641} INFO - Using properties file: null
[2024-12-31T09:15:48.560+0100] {spark_submit.py:641} INFO - 24/12/31 09:15:48 WARN Utils: Your hostname, NB04 resolves to a loopback address: 127.0.1.1; using 192.168.178.24 instead (on interface wlp0s20f3)
[2024-12-31T09:15:48.562+0100] {spark_submit.py:641} INFO - 24/12/31 09:15:48 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-12-31T09:15:48.637+0100] {spark_submit.py:641} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-12-31T09:15:48.638+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-12-31T09:15:48.638+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-12-31T09:15:48.638+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-12-31T09:15:48.638+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-12-31T09:15:48.638+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-12-31T09:15:48.639+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-12-31T09:15:48.639+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-12-31T09:15:48.639+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-31T09:15:48.639+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-31T09:15:48.639+0100] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-31T09:15:48.671+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /home/maxpower/airflow/dags/amazon_v2_cleanup.py. Error code is: 1.
[2024-12-31T09:15:48.676+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=run_pyspark_etl, run_id=manual__2024-12-31T08:06:36.183790+00:00, execution_date=20241231T080636, start_date=20241231T081547, end_date=20241231T081548
[2024-12-31T09:15:48.688+0100] {logging_mixin.py:190} WARNING - /home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-12-31T09:15:48.689+0100] {configuration.py:1074} WARNING - section/key [smtp/smtp_user] not found in config
[2024-12-31T09:15:48.689+0100] {email.py:272} INFO - Email alerting: attempt 1
[2024-12-31T09:15:48.691+0100] {configuration.py:1074} WARNING - section/key [smtp/smtp_user] not found in config
[2024-12-31T09:15:48.691+0100] {email.py:272} INFO - Email alerting: attempt 1
[2024-12-31T09:15:48.691+0100] {taskinstance.py:1234} ERROR - Failed to send email to: ['admin@example.com']
Traceback (most recent call last):
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /home/maxpower/airflow/dags/amazon_v2_cleanup.py. Error code is: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1442, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/home/maxpower/miniconda3/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1232, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3605, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1444, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/home/maxpower/miniconda3/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-12-31T09:15:48.700+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-31T09:15:48.701+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task run_pyspark_etl (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /home/maxpower/airflow/dags/amazon_v2_cleanup.py. Error code is: 1.; 14653)
Traceback (most recent call last):
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/maxpower/miniconda3/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /home/maxpower/airflow/dags/amazon_v2_cleanup.py. Error code is: 1.
[2024-12-31T09:15:48.720+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-31T09:15:48.737+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-31T09:15:48.743+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
